"""Cria tabela de planos de vipagem

Revision ID: 0a9fd52b472e
Revises: b403439c9946
Create Date: 2026-07-30 13:40:52.676858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9fd52b472e'
down_revision = 'b403439c9946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vip_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('room_number_override', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('delivery_status', sa.String(length=30), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vip_plans')
    # ### end Alembic commands ###
