"""Adiciona rate_code em Reservation

Revision ID: 1a1c9438cfb6
Revises: 8301e98c75e9
Create Date: 2026-09-08 09:57:18.265217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1c9438cfb6'
down_revision = '8301e98c75e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('rate_code')

    # ### end Alembic commands ###
