"""Cria tabela institutional_dates

Revision ID: 33570eac56c8
Revises: c578ecdb4876
Create Date: 2026-08-09 10:49:34.372116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33570eac56c8'
down_revision = 'c578ecdb4876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institutional_dates')
    # ### end Alembic commands ###
