"""Importacao Opera Cloud: ReservationNote, dept_traces, opera_rate_code

Revision ID: 34c2442a159b
Revises: c4572c5bb013
Create Date: 2026-08-16 12:40:15.181327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c2442a159b'
down_revision = 'c4572c5bb013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('comment_type', sa.String(length=20), nullable=False),
    sa.Column('order_by', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opera_rate_code', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_categories_opera_rate_code', ['opera_rate_code'])

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_traces', sa.Text(), nullable=True))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###

    op.execute(
        "UPDATE categories SET scope = 'stay' WHERE name IN "
        "('ALL Signature Zen Day', 'ALL Signature Fondue', 'ALL Signature ALL Kids')"
    )
    op.execute(
        "UPDATE categories SET manual_only = 1 WHERE name = 'Pedido de Desculpas'"
    )


def downgrade():
    op.execute(
        "UPDATE categories SET scope = 'guest' WHERE name IN "
        "('ALL Signature Zen Day', 'ALL Signature Fondue', 'ALL Signature ALL Kids')"
    )
    op.execute(
        "UPDATE categories SET manual_only = 0 WHERE name = 'Pedido de Desculpas'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.drop_column('dept_traces')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_categories_opera_rate_code', type_='unique')
        batch_op.drop_column('opera_rate_code')

    op.drop_table('reservation_notes')
    # ### end Alembic commands ###
