"""Cria guest_badges, adiciona opera_guest_id e notes

Revision ID: 6ac2cc539f41
Revises: a2a4cd39ed83
Create Date: 2026-08-03 10:15:42.856395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac2cc539f41'
down_revision = 'a2a4cd39ed83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opera_guest_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_guests_opera_guest_id', ['opera_guest_id'])
        batch_op.drop_column('vip_category')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip_category', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('uq_guests_opera_guest_id', type_='unique')
        batch_op.drop_column('opera_guest_id')

    op.drop_table('guest_badges')
    # ### end Alembic commands ###
