"""Cria tabelas de ImportLog e ImportError

Revision ID: 6e00db0bda48
Revises: 34c2442a159b
Create Date: 2026-08-24 15:17:56.960507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e00db0bda48'
down_revision = '34c2442a159b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_by_id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('total_reservations', sa.Integer(), nullable=False),
    sa.Column('total_created', sa.Integer(), nullable=False),
    sa.Column('total_updated', sa.Integer(), nullable=False),
    sa.Column('total_cancelled', sa.Integer(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], name='fk_import_logs_imported_by_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_import_logs')
    )
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_log_id', sa.Integer(), nullable=False),
    sa.Column('confirmation_no', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], name='fk_import_errors_import_log_id_import_logs'),
    sa.PrimaryKeyConstraint('id', name='pk_import_errors')
    )
    with op.batch_alter_table('import_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_errors_import_log_id'), ['import_log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_errors_import_log_id'))

    op.drop_table('import_errors')
    op.drop_table('import_logs')
    # ### end Alembic commands ###
