"""Adiciona Category, StayBadge, ItemType, CategoryItemTemplate, GuestLink; ajusta GuestBadge, VipItem, Reservation

Revision ID: 730b36ea5422
Revises: 6ac2cc539f41
Create Date: 2026-08-03 14:29:41.650362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730b36ea5422'
down_revision = '6ac2cc539f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('suggestion_priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_category', sa.String(length=30), nullable=False),
    sa.Column('assembly_instructions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category_item_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('requires_child', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'item_type_id', 'requires_child', name='uq_category_item_templates_category_item_child')
    )
    op.create_table('guest_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_guest_id', sa.Integer(), nullable=False),
    sa.Column('secondary_guest_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['primary_guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['secondary_guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary_guest_id', 'secondary_guest_id', name='uq_guest_links_primary_secondary')
    )
    op.create_table('stay_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_guest_badges_category_id_categories', 'categories', ['category_id'], ['id'])
        batch_op.drop_column('label')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_eta', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('contact_status', sa.String(length=20), nullable=False, server_default='pendente'))

    with op.batch_alter_table('vip_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type_id', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_foreign_key('fk_vip_items_item_type_id_item_types', 'item_types', ['item_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vip_items_item_type_id_item_types', type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('item_type_id')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('contact_status')
        batch_op.drop_column('confirmed_eta')

    with op.batch_alter_table('guest_badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_guest_badges_category_id_categories', type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('stay_badges')
    op.drop_table('guest_links')
    op.drop_table('category_item_templates')
    op.drop_table('item_types')
    op.drop_table('categories')
    # ### end Alembic commands ###
