"""Adiciona title em ReservationNote

Revision ID: 9661f62cc092
Revises: 1a1c9438cfb6
Create Date: 2026-09-08 10:17:19.815482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9661f62cc092'
down_revision = '1a1c9438cfb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_notes', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
