"""Adiciona always_apply e manual_only a Category, torna suggestion_priority nullable, cria CategoryKeyword

Revision ID: aea187b152c4
Revises: 730b36ea5422
Create Date: 2026-08-06 10:00:29.036836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea187b152c4'
down_revision = '730b36ea5422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('always_apply', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('manual_only', sa.Boolean(), nullable=False))
        batch_op.alter_column('suggestion_priority',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('suggestion_priority',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('manual_only')
        batch_op.drop_column('always_apply')

    op.drop_table('category_keywords')
    # ### end Alembic commands ###
