"""Adiciona matched_keyword, matched_note_type e origin_missing a StayBadge

Revision ID: bb9bdfe3679b
Revises: 9661f62cc092
Create Date: 2026-09-14 12:09:46.285718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9bdfe3679b'
down_revision = '9661f62cc092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_keyword', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('matched_note_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('origin_missing', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_badges', schema=None) as batch_op:
        batch_op.drop_column('origin_missing')
        batch_op.drop_column('matched_note_type')
        batch_op.drop_column('matched_keyword')

    # ### end Alembic commands ###
