"""Adiciona opera_status, is_shared, adults e children em Reservation

Revision ID: c161f11a4dd5
Revises: 6e00db0bda48
Create Date: 2026-08-26 13:13:16.346590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c161f11a4dd5'
down_revision = '6e00db0bda48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opera_status', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('adults', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('children', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('children')
        batch_op.drop_column('adults')
        batch_op.drop_column('is_shared')
        batch_op.drop_column('opera_status')

    # ### end Alembic commands ###
