"""Cria tabelas de memorando e adiciona preparation_sector

Revision ID: c4572c5bb013
Revises: 33570eac56c8
Create Date: 2026-08-12 14:06:11.170959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4572c5bb013'
down_revision = '33570eac56c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memorandos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('vip_plan_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('previous_version_id', sa.Integer(), nullable=True),
    sa.Column('status_versao', sa.String(length=20), nullable=False),
    sa.Column('responsavel_interno_id', sa.Integer(), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pax_adultos', sa.Integer(), nullable=True),
    sa.Column('pax_criancas_6_12', sa.Integer(), nullable=True),
    sa.Column('pax_criancas_ate_5', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['memorandos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_interno_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vip_plan_id'], ['vip_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memorando_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memorando_id', sa.Integer(), nullable=False),
    sa.Column('vip_item_id', sa.Integer(), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('horario', sa.String(length=5), nullable=True),
    sa.Column('pax', sa.Integer(), nullable=True),
    sa.Column('descricao_observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.id'], ),
    sa.ForeignKeyConstraint(['memorando_id'], ['memorandos.id'], ),
    sa.ForeignKeyConstraint(['vip_item_id'], ['vip_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preparation_sector', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.drop_column('preparation_sector')

    op.drop_table('memorando_lines')
    op.drop_table('memorandos')
    # ### end Alembic commands ###
