"""Adiciona preferences em Guest

Revision ID: c578ecdb4876
Revises: c70c5df8e7e3
Create Date: 2026-08-09 10:35:28.160985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c578ecdb4876'
down_revision = 'c70c5df8e7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('preferences')

    # ### end Alembic commands ###
