"""Adiciona ready_for_delivery em VipPlan

Revision ID: c70c5df8e7e3
Revises: aea187b152c4
Create Date: 2026-08-09 10:24:46.099928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70c5df8e7e3'
down_revision = 'aea187b152c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ready_for_delivery', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip_plans', schema=None) as batch_op:
        batch_op.drop_column('ready_for_delivery')

    # ### end Alembic commands ###
