"""Cria tabela de itens de vipagem

Revision ID: e12448617514
Revises: 0a9fd52b472e
Create Date: 2026-07-30 14:14:57.374939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12448617514'
down_revision = '0a9fd52b472e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vip_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vip_plan_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=False),
    sa.Column('availability_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vip_plan_id'], ['vip_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vip_items')
    # ### end Alembic commands ###
